/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class RSQLite {
  constructor()
  open(path: string): void
  exec(sql: string): number
  query(sql: string): string
}
